version: "3"

services:
  discovery:
    build:
      context: .
      dockerfile: docker/Dockerfile.discovery
    container_name: smesh-discovery
    ports:
      - "8000:8000"
    networks:
      meshnet:
        ipv4_address: 172.20.0.2
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    command: python server/discovery_server.py
    volumes:
      - ./server:/app/server

  client1:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: smesh-client1
    depends_on:
      - discovery
    networks:
      meshnet:
        ipv4_address: 172.20.0.10
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1 # Enable IP forwarding
    devices:
      - /dev/net/tun:/dev/net/tun
    command: sh -c "sleep 2 && python client/client.py"
    restart: unless-stopped
    environment:
      - HTTP_SERVER=true
      - DISCOVERY_SERVER=172.20.0.2:8000
      - IP_ADDRESS=10.10.0.10
      - PORT=9010
      - PYTHONUNBUFFERED=1
      - INTERFACE_NAME=smesh_tun1
    volumes:
      - ./client:/app/client

  client2:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: smesh-client2
    depends_on:
      - discovery
      - client1
    networks:
      meshnet:
        ipv4_address: 172.20.0.20
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1 # Enable IP forwarding
    devices:
      - /dev/net/tun:/dev/net/tun
    command: sh -c "sleep 5 && python client/client.py"
    restart: unless-stopped
    environment:
      - HTTP_SERVER=true
      - DISCOVERY_SERVER=172.20.0.2:8000
      - IP_ADDRESS=10.10.0.20
      - PORT=9020
      - PYTHONUNBUFFERED=1
      - INTERFACE_NAME=smesh_tun2
    volumes:
      - ./client:/app/client

  client3:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: smesh-client3
    depends_on:
      - discovery
      - client2
    networks:
      meshnet:
        ipv4_address: 172.20.0.30
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1 # Enable IP forwarding
    devices:
      - /dev/net/tun:/dev/net/tun
    command: sh -c "sleep 8 && python client/client.py"
    restart: unless-stopped
    environment:
      - HTTP_SERVER=true
      - DISCOVERY_SERVER=172.20.0.2:8000
      - IP_ADDRESS=10.10.0.30
      - PORT=9030
      - PYTHONUNBUFFERED=1
      - INTERFACE_NAME=smesh_tun3
    volumes:
      - ./client:/app/client

networks:
  meshnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
