FROM python:3.13-slim

WORKDIR /app

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install Python dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy application files
COPY . .

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Expose discovery server port
EXPOSE 8000

# Default command
CMD ["python", "server/discovery_server.py"]